#!/bin/sh
# Build third party software
make dodeps
# Build Obit with AVX2 (and earlier) vector instructions
CPPFLAGS="-msse -DHAVE_SSE=1 -mavx -DHAVE_AVX -mavx2 -DHAVE_AVX2=1"; export CPPFLAGS
VTYPE="AVX2"; export VTYPE
echo $CPPFLAGS $VTYPE
echo $VTYPE>VectorType
make target
