#!/bin/sh
# Build third party software
make dodeps
# Build Obit with AVX vector instructions
CPPFLAGS="-msse -mavx -DHAVE_SSE=1 -DHAVE_AVX"; export CPPFLAGS
VTYPE="AVX"; export VTYPE
echo $CPPFLAGS $VFLAGS
echo $VTYPE>VectorType
make target
